version: "3.4"

services:
  php:
    build:
      context: .
      target: app_php_dev
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  db:
    image: postgres:${POSTGRES_VERSION}-alpine
    env_file:
      - .env
    restart: always
    ports:
      - "3307:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  php_socket:
  db_data:
