name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull images
        run: docker compose pull
      - name: Start services
        run: docker compose up --build -d
      - name: Wait for services
        run: |
          while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker compose ps -q php)")"; do
            case $status in
              starting) sleep 1;;
              healthy) exit 0;;
              unhealthy) exit 1;;
            esac
          done
          exit 1
      - name: Create test database
        run: docker-compose exec -T php bin/console -e test doctrine:database:create
      - name: Create database schema
        run: docker-compose exec -T php bin/console -e test doctrine:schema:update --force
      - name: Load fixtures
        run: docker-compose exec -T php bin/console -e test doctrine:fixtures:load --no-interaction
      - name: PHPUnit
        run: docker-compose exec -T php bin/phpunit
